export const SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'AUTH/REMOVE_CURRENT_USER';
export const LOGOUT_FAILED = 'AUTH/LOGOUT_FAILED';
export const UPDATE_FORM = 'AUTH/UPDATE_FORM';
export const UPDATE_STEP = 'AUTH/UPDATE_STEP';
export const CLEAR_FORM = 'AUTH/CLEAR_FORM';